name: "🐛 Bug Report"
description: We broke something, again
title: "[Bug]: "
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting an issue!** Please make sure you read our [issue guidelines](https://github.com/lamah-co/it-projects-template/blob/main/.github/CONTRIBUTING.md) first, then fill out the fields below.

        If you’re unsure whether the issue you’re having is a bug, you can get in contact with the team instead.

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1. Make new project
        2. Run `make package`
        3. …
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: true

  - type: textarea
    id: bug-logs
    attributes:
      label: Paste any relevant logs, error output, etc.
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        (If it’s long, please paste to https://gist.github.com/ and insert the link here.)
      render: shell

  - type: textarea
    id: bug-context
    attributes:
      label: Additional context
      description: Add any other context you can provide about the problem here.

  - type: markdown
    attributes:
      value: |
        ----

        # Details of your host machine (the device you’re running this project on)

  - type: dropdown
    id: host-os
    attributes:
      label: What OS are you seeing the problem on?
      options:
        - iOS
        - macOS
        - Linux/WSL
        - Cygwin
      multiple: true
    validations:
      required: true

  - type: input
    id: host-os-version
    attributes:
      label: What OS version does it have installed?
      placeholder: "e.g. macOS 11.5.1"
    validations:
      required: true

  - type: input
    id: host-sdk
    attributes:
      label: Which SDK version are you using?
      placeholder: "e.g. iOS 14.0"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ----

        # Details of your client device (the device you’re attempting to run your code on)

  - type: dropdown
    id: client-os
    attributes:
      label: What OS is your client device running?
      options:
        - iOS
        - macOS
        - Linux/WSL
        - Cygwin
      multiple: true
    validations:
      required: true

  - type: input
    id: client-os-version
    attributes:
      label: What OS version does it have installed?
      placeholder: "e.g. iOS 14.0"
    validations:
      required: true

  - type: input
    id: client-model
    attributes:
      label: Which device model is it?
      placeholder: "e.g. iPhone X"
    validations:
      required: true
