name: Enhancement Suggestion
description: Suggest an enhancement for this project
title: "Enhancement: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement suggestion!
  - type: textarea
    id: problem-description
    attributes:
      label: Is your enhancement request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the enhancement request here.
